print('*** Receta de Cocina ***')
nombre_plato = input('Inglesa el nombre: ')
ingredientes = input('Ingresa los ingredientes: ')
tiempo_preparacion = int(input('Ingresa el tiempo de preparación (min): '))
dificultad = input('Ingres la dificutad: ')
print('----------------')
print(f'Nombre receta: {nombre_plato}')
print(f'Ingredientes: {ingredientes}')
print(f'Tiempoo de preparación: {tiempo_preparacion}')
print(f'Dificultad: {dificultad}')